#!/bin/bash

if [ $# = 0 ]; then
    cat <<EOF
Usage: $(basename "${0}") process_name [executable_name] [--take-first]
    process_name       As recognized by 'xdo' command
    executable_name    As used for launching from terminal
    --take-first       In case 'xdo' returns multiple process IDs
EOF
    exit 0
fi

# Get id of process by class name and then fallback to instance name
exec_name=$(head -1 <<<"${1}" | cut -f1 -d' ')
id=$(xdo id -N "${exec_name}" || xdo id -n "${exec_name}")

executable=${1}
shift

while [ -n "${1}" ]; do
    case ${1} in
    --take-first)
        id=$(head -1 <<<"${id}" | cut -f1 -d' ')
        ;;
    *)
        executable=${1}
        ;;
    esac
    shift
done

if [ -z "${id}" ]; then
#    exec_id=$(xdo id -N "${exec_name}" || xdo id -n "${exec_name}")
#    executable="${executable}; sleep 0.4; bspc node \$(xdo id -N \"${exec_name}\" || xdo id -n \"${exec_name}\") -t floating -g sticky"
    # bspc rule -a \* -o state=floating && ${executable}&
    ~/bin/bspwm-floatwin && ${executable}&
    #read  -n 1 -p "Input Selection:" mainmenuinput
    #sleep 2;bspc node $(xdo id -N "${exec_name}" || xdo id -n "${exec_name}") -t floating -g sticky
else
    while read -r instance; do
        bspc node "${instance}" --flag hidden --to-monitor focused --focus
        bspc node "${id}" -t floating -g sticky
    done <<<"${id}"
fi
